### ISSUE TITLE
Generic error NO_PAYMENT_METHOD_ERROR

### ISSUE THREAD

**Issue by juongithub** [braintree/braintree-web-drop-in#113]
The dropin returns always the error NO_PAYMENT_METHOD_ERROR for all failures regarding credit cards.
It could be useful to get "real errors" returned by the payment gateway (e.g., the gateway returns "Duplicate card exists in the vault" for duplicate credit cards).

**Comment by intelliot** [comment]
Thanks for the suggestion! We'll keep your request in mind for the future when we look at ways to improve the errors returned by Drop-in.

**Comment by crookedneighbor** [comment]
@juongithub Do you as the merchant need those specific errors? Or is it enough for a more descriptive error to populate on the front end for the customer to read? 

This PR updates Drop-in so that the customer is given a better understanding of what they need to do to fix the problem, but passes back the same error to the merchant. 
https://github.com/braintree/braintree-web-drop-in/pull/133

I can't think of any reason the merchant would need to know the specific reason for the failure, but I'm happy to listen if you have a specific use case.

**Comment by juongithub** [comment]
@crookedneighbor thanks for the reply. 
A merchant may want to avoid duplicate payment methods (failOnDuplicatePaymentMethod=true); in this case, a user who is entering a credit card (that was already entered) may see a misleading error message. If I were a user, the message "invalid payment method" would lead me to double-check the credit card info and eventually to contact the customer support, but not that the credit card was already used.

**Comment by crookedneighbor** [comment]
Beta 7 was just released which includes a `_braintreeWebError` property on errors if the source of the error was a Braintree error.

This release also includes messaging to the user if the reason tokenization failed was because of cvv verification failing.

```
<script src="https://js.braintreegateway.com/web/dropin/1.0.0-beta.7/js/dropin.min.js"></script>
```

**Comment by juongithub** [comment]
Thanks :)

**Comment by simeyla** [comment]
@crookedneighbor  Isn't `_braintreeWebError` a private field we aren't supposed to access.

Has this since been promoted to a 'supported' field? Thanks

**Comment by crookedneighbor** [comment]
You shouldn't do anything programatic based on the value in your app, but it can be useful to inspect it to find the root of the error when debugging.
