### ISSUE TITLE
PayPal sandbox: "PayPal pending payments are not supported"

### ISSUE THREAD

**Issue by NinoSkopac** [braintree/braintree-web-drop-in#161]
So, I migrated from beta-6 to 1.0.1, and I had to go the through the incoherent and very annoying process of linking PayPal sandbox account.

So, in the essence, I've linked my facilitator account to braintree sandbox, and tried to pay through my PP buyer sandbox account, but after logging in... well this is annoying even to describe, so here's a video: https://drive.google.com/open?id=0B7AKQvQJ6zw2Q0NzR0Zya0F0eWs

i liked the simplicity of using PP sandbox previously, this is just pure AIDS.
also, PP loading is very slow (are you using CDNs? I'm in Amsterdam)

**Comment by crookedneighbor** [comment]
I can't think of a good reason for you to get that error. Can you provide a staging site for us to debug why you are getting the `PayPal pending payments are not supported` error? If you'd prefer not to post a staging url publicly, you can email support@braintreepayments.com and reference this issue.

The PayPal Checkout script is [provided via a CDN](https://github.com/braintree/braintree-web-drop-in/blob/f4eeacc848a162e38b57a476362e75300f2b5b92/src/dropin.js#L140-L148). We do this rather than bundling it in because the PayPal iframe that checkout.js loads on the page also includes the file from the CDN, so by loading it dynamically it's already cached by the browser when the iframe loads it.

As far as speed goes, PayPal production should be significantly faster in production than it is in sandbox. Can you confirm if the speed issues you are experiencing occur in a production environment as well?

**Comment by NinoSkopac** [comment]
I've sent an email containing username/password for basic auth. 
Sorry for my tone from original message, I was really annoyed with paypal.

> Can you confirm if the speed issues you are experiencing occur in a production environment as well?
Can't right now cause the version I'm working on right now is not ready for production yet, but I'll try to remember to update you once it goes live (I'm still using beta-5 on production and _that_ once is so slow I had to provide my own "Processing ..." indicator)

**Comment by crookedneighbor** [comment]
Okay, so we've tracked down the problem. It looks like your sandbox account is setup to block payments from PayPal accounts with different currencies than the one you're making the request with.

![pasted_image_at_2017_05_15_09_43_am_480](https://cloud.githubusercontent.com/assets/2916945/26063704/64c610ee-3954-11e7-8a7e-4d5d25412f52.png)

If this is the behavior you want, you will need to create a test customer account with the same currency that you're using with the setup of Drop-in.

If this is _not_ the behavior you want, you can log into sandbox.paypal.com and go to `Profile > My Selling Tools > Block Payments` to adjust the setting or `Profile > My Money > PayPal Balance section > More > Currencies` to add the currency of the account you are trying to use.

**Comment by NinoSkopac** [comment]
that fixed it. thanks.

**Comment by loganstellway** [comment]
Helpful note to find the **Payment Reviews** settings for PayPal users utilizing `developer.paypal.com`:
- Login to [`developer.paypal.com`](https://developer.paypal.com/)
- Navigate to `Sandbox > Accounts`
- Expand the account & click `Profile`
- Navigate to `Settings > Payment Review`

**Comment by allgama** [comment]
I already did activate the option following the @loganstellway instructions, but I receive the same error. I activated the option with my merchant account and the personal account, but nothing, some other idea??

**Comment by crookedneighbor** [comment]
@allgama Please contact our support team so we can inspect your account and help you figure it out: https://articles.braintreepayments.com/forms/contact

**Comment by atta1234** [comment]
i did that step but still getting the same message,,,,when i not use brain tree the pay-pal stand smart button working, but the issue occur when i use brain tree

**Comment by crookedneighbor** [comment]
Our support team is the best equipped to troubleshoot issues with your integration: https://help.braintreepayments.com/
