### ISSUE TITLE
Drop dependency on remote subresource

### ISSUE THREAD

**Issue by buu700** [braintree/braintree-web-drop-in#163]
This module currently depends on loading its css remotely from https://assets.braintreegateway.com/web/dropin/1.0.2/css/dropin.css, which is blocked by our CSP and breaks the payment form UI.

We're able to temporarily work around this issue by directly including dropin.css in our project source, but it'd be preferable if dropin.css were included in the npm package and only downloaded from assets.braintreegateway.com at run-time if it couldn't be determined that the necessary styling had already been loaded.

**Comment by buu700** [comment]
On a related note, it'd be nice if there were a way to enable a PayPal flow without loading their remote JavaScript. In our case, we didn't really need PayPal checkout (and had been considering removing it irrespective of the SDK v3 upgrade), so just disabling it was a good enough mitigation; but I could see this being a bigger problem for other Braintree users.

**Comment by crookedneighbor** [comment]
For the css, if you provide a stylesheet with an id of `braintree-dropin-stylesheet`, it will not load the external css. So you can download the css on your server and use that instead. You can see an example here, in our test app: https://github.com/braintree/braintree-web-drop-in/blob/f4eeacc848a162e38b57a476362e75300f2b5b92/test/app/index.html#L5

I'll see about adding the compiled css to the npm package. I think that would be a good addition. 

Thank you for your feedback about the PayPal assets, but we have no plans to change how it works at this time. PayPal recommends all integrations use their [checkout.js script](https://github.com/paypal/paypal-checkout), so that's what we've done. We _could_ bundle it in via npm, but the CDN version of the assets would need to be downloaded anyway for use in the iframe. Using the CDN up front means that it can be already cached for the iframe to use (and reduces the size of the module/script on initial download).

**Comment by buu700** [comment]
Thanks! The `braintree-dropin-stylesheet` solution was what I ended up going with yesterday, which seems basically fine to me as long as I can trust that future releases will remain backwards compatible with this solution (and ideally I think it should probably be documented somewhere for others with similar requirements).

**Comment by crookedneighbor** [comment]
We're going to go ahead and add the compiled CSS to the npm package so people who want to host the css locally can do so without having the versions go out of sync. I'll update here when it is done.

**Comment by buu700** [comment]
Nice, thanks!

**Comment by crookedneighbor** [comment]
Gonna re-open this until we've actually published to npm.

**Comment by crookedneighbor** [comment]
1.1.0 is on NPM and now provides the built css file.
