### ISSUE TITLE
3D Secure support ?

### ISSUE THREAD

**Issue by MixMe** [braintree/braintree-web-drop-in#208]
3D secure is supported ?

**Comment by crookedneighbor** [comment]
Built in 3D Secure has not been added, but will be in the future.

You can still use 3D Secure with Drop-in by including the braintree-web client and 3D Secure components on the page and using the `nonce` provided by `requestPaymentMethod` to verify the card.

Here's a codepen illustrating how to do it: https://codepen.io/braintree/pen/BZWdmy

I will leave this issue open until we've added 3D Secure directly to Drop-in.

**Comment by MixMe** [comment]
okey, thx ;)

**Comment by MixMe** [comment]
In your example, if i close 3D secure window and click "Pay Now" again, 3d secure windows is not appear

**Comment by crookedneighbor** [comment]
I had a mistake in my example, I've updated it now to be correct.

Basically, what happens when you verify a card with 3ds with the nonce from Drop-in is that the nonce is consumed and can no longer be used for anything, but Drop-in has no way of knowing that the nonce it has is consumed, so attempting to verify again with the original nonce will fail.

I've updated the example to provide the 3ds nonce info when the flow is cancelled. The nonce included in the payload can be used to create the transaction. If you do not want to proceed with the transaction, you'll have to handle resetting drop-in (by leveraging [teardown](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#teardown), or reloading the page, etc)

When 3ds is built into Drop-in, all of this will be handled internally.

**Comment by MixMe** [comment]
okey, thx ;)

**Comment by crookedneighbor** [comment]
Going to keep this open for now until we add 3DS to directly to drop-in.

**Comment by haraldpdl** [comment]
Is there a method to change the 3DS instance amount dynamically similar to the new updateConfiguration method for PayPal amounts?

**Comment by crookedneighbor** [comment]
Released in 1.9.0 https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#changelog
