### ISSUE TITLE
Iframe issue for paypal loading

### ISSUE THREAD

**Issue by Chocksy** [braintree/braintree-web-drop-in#287]
### General information

* SDK/Library version: 1.8.0 dropin
* Environment: Production & Sandbox
* All browsers

### Issue description

We are using the braintree dropin on our website epicpxls.com and we have an external script that allows for a modal to be integrated into the page. An example of this is here: [rainbow](https://rainbow.epicpxls.com/) we are loading the dropin inside the modal that is loaded using an iframe like so: [picture](http://take.ms/rCCji)

Problem: when trying to click on paypal we get an error that seems to be resolved when adding the paypal/checkout.js script in the parent. The issue is exactly this one https://github.com/paypal/paypal-checkout/issues/140
Is there any other way for us to do this besides adding the paypal-checkout script in the parent when the modal appears? Maybe have a detection in the drop-in script or is that too much to ask?

**Comment by crookedneighbor** [comment]
PayPal's checkout.js requires that the script be on the top element of the page to work. We've asked them to provide some kind of solution for when this is not the case, but they have not implemented anything. 

The only way to resolve it is to include the checkout.js script on the parent page. By default, Drop-in pins to specific a version of checkout.js. If you provide your own checkout.js script tag on the page, it will use that one instead. To ensure that the versions used in the iframe and the parent page match, I recommend putting the same script tag on both.

Can you explain what you mean by

> Maybe have a detection in the drop-in script or is that too much to ask?

I'm not sure what you're asking there.

**Comment by Chocksy** [comment]
What i mean is if we can detect if the drop-in is in an iframe and add the checkout.js in the parent of the iframe. I know it's not possible 100% from the script but maybe with an event or something similar.

**Comment by crookedneighbor** [comment]
There's definitely a way to detect if it's in an iframe. For instance: https://stackoverflow.com/questions/326069/how-to-identify-if-a-webpage-is-being-loaded-inside-an-iframe-or-directly-into-t

But there's no way for Drop-in to insert the script automatically in the parent page (by the nature of how iframes work), so you would still need to do that yourself. 

Going to close this, because I don't think there's anything actionable for us to do in the SDK, but feel free to comment here if you have more questions about this.
