### ISSUE TITLE
braintree-placeholder is adding unnecessary height

### ISSUE THREAD

**Issue by ernsheong** [braintree/braintree-web-drop-in#312]
### General information

* SDK/Library version: 1.8.1
* Browser and OS: Chrome 62 on macOS Sierra

### Issue description

Additional height is being added by `&nbsp;` character in `braintree-placeholder`:

![image](https://user-images.githubusercontent.com/1343284/32317482-e3a8531a-bfee-11e7-84e0-c9b3704c6b40.png)
![image](https://user-images.githubusercontent.com/1343284/32317566-21e03bde-bfef-11e7-93d2-1fb2eb5a15a8.png)

Can we get rid of the `$nbsp;` character that is giving additional height?

**Comment by crookedneighbor** [comment]
That's there intentionally. When a card is tokenized, a heading appears that says "Pay with Card" in the place of that blank section. See:

![placeholder](https://user-images.githubusercontent.com/2916945/32326623-842008d6-bfa1-11e7-97d0-c847f542b2de.gif)

If we remove the `braintree-placeholder` section, we would also need to apply some awkward height resizing to show those headings. 

You can always use css to hide the `braintree-placeholder` div, but you will also visually lose the headings because of it (as they will be hidden behind drop-in).

**Comment by ernsheong** [comment]
Ic, thanks.

**Comment by toxaq** [comment]
It might be there by intention but it doesn't mean it's a good flow. If you're going straight to the card entry details, it just looks like you've done something wrong...

<img width="556" alt="screen shot 2017-11-07 at 1 36 22 pm" src="https://user-images.githubusercontent.com/1203104/32471149-bd9fb8e0-c3c0-11e7-956b-5311e834bd39.png">

Designers are crying in their soy trim lattes... I also don't see why the space can't be animated away if it does come from the card selection menu first?

**Comment by trisys3** [comment]
I agree with @crookedneighbor's concerns about the spacing needing to be there for consistency reasons. At least, all the designers I have worked with agree with him. However, it still looks like something is wrong while you're on a single payment method. Also, if this isn't the only thing on the page, like if it's in a tooltip or something, the user could easily forget the header was ever supposed to be there.

Just my 2 cents.

**Comment by RicLeP** [comment]
A solution would be to remove the `&nbsp;` from the placeholder so we could use css `:empty` and `display: none;` to hide it, then it could be filled when the heading is shown. Currently it makes attractive layouts really akward as the space is too large without the heading shown.

Or remove the placeholder and change how the item animates in.

**Comment by mihai-dinculescu** [comment]
> 
> 
> A solution would be to remove the `&nbsp;` from the placeholder so we could use css `:empty` and `display: none;` to hide it, then it could be filled when the heading is shown. Currently it makes attractive layouts really akward as the space is too large without the heading shown.
> 
> Or remove the placeholder and change how the item animates in.
> 
> **Update**
> 
> Adding the following will move the vard box up. This class is replaced with `.braintree-show-methods` once details are entered which removes the negative margin..
> 
> ```
> .braintree-show-card {
> 	margin-top: -30px;
> }
> ```

This works pretty well. Thanks!

**Comment by JohanRonstrom** [comment]
My intention is to hide the headers via CSS. I can of course also hide the placeholder, you write in your documentation:

>  do not recommend applying styles based on Braintree provided class names

There does not seem to be a way to hide the headers of my all card payment flow without getting annoying whitespace or using the class. Since the classname is so vague, I'm not sure that it is (or will be) used elsewhere.. A solution to this could be to also add a unique data attribute to this specific placeholder.

**Comment by dminkovsky** [comment]
> You can always use css to hide the braintree-placeholder div, but you will also visually lose the headings because of it (as they will be hidden behind drop-in).

Why can't this library just show/hide this div when there's something that needs to be inside of it? This is a serious visual problem.

**Comment by dminkovsky** [comment]
How am I supposed to convince users to give me $4.99/mo with this gap here?

<img width="331" alt="Screen Shot 2020-08-11 at 6 05 44 PM" src="https://user-images.githubusercontent.com/218725/89953607-666f4b00-dbfd-11ea-9ec9-7ec2fd6526bd.png">

**Comment by crookedneighbor** [comment]
Thanks for the feedback! I'm logging this issue with a "Design Feedback" label so we can address these concerns when we start working on the redesign for Drop-in in the next major version.
