### ISSUE TITLE
Paypal button doesn't work on IE11

### ISSUE THREAD

**Issue by chhuang** [braintree/braintree-web-drop-in#361]
### General information

* SDK/Library version: 3/1.9.4
* Environment: Production
* Browser and OS: IE 11

### Issue description
The paypal button doesn't work on IE11. This could be related to the promise error.

Tested on my local and also:
https://developers.braintreepayments.com/guides/drop-in/overview/javascript/v3

![screen shot 2018-02-16 at 3 57 57 pm](https://user-images.githubusercontent.com/78710/36294421-b891174a-1334-11e8-8436-fb86123b1b82.png)

**Comment by crookedneighbor** [comment]
It's unrelated to the promise polyfill error. The error is happening in checkout.js, which Drop-in uses. I've opened up an issue in that repo: https://github.com/paypal/paypal-checkout/issues/609

I recommend subscribing to that issue if you'd like to follow along. Once the bug is fixed and released in checkout.js, it'll automatically start working in Drop-in.

Going to close this issue now, since there's nothing actionable for us to do.

**Comment by crookedneighbor** [comment]
The checkout.js release has been rolled back, so this should be working again.
