### ISSUE TITLE
Feature Request: Indicating that users need to click the inner "PayPal Checkout" button for PayPal and PayPal Credit

### ISSUE THREAD

**Issue by AlbinoDrought** [braintree/braintree-web-drop-in#433]
### General information

* SDK/Library version: braintree-web-drop-in@1.11.0
* Environment: Sandbox and Production
* Browser and OS: All

### Issue description

As an integrator of the Braintree Web Drop-in, I want my users to understand that they need to click the "PayPal Checkout" button _inside_ the "PayPal" option so they can continue, without confusion, checking out.

---

This is something that has been brought to my attention recently, and although it's intuitive to me, it seems like it may not be intuitive for all.

In this section:

![image](https://user-images.githubusercontent.com/852873/45895801-0102de80-bd87-11e8-9c13-2a3e078a2bea.png)

Users are clicking the "PayPal" or "PayPal Credit" options and not realizing they still need to click the "inner button" to complete the PayPal checkout flow:

![image](https://user-images.githubusercontent.com/852873/45895842-2a236f00-bd87-11e8-9864-48e831fdda4c.png)

Although I could badger the user with some errors when they try to continue, I was thinking something like the credit card validation errors might be nice: (these are shown when calling `requestPaymentMethod` when no payment method is requestable)

![image](https://user-images.githubusercontent.com/852873/45895912-5e972b00-bd87-11e8-899f-42da60a25b56.png)

I'm imagining something like this but possibly with a different error message: (I'm not very good with those things...)

![image](https://user-images.githubusercontent.com/852873/45896210-4542ae80-bd88-11e8-8fa0-14e94f0814ba.png)

I'm also open to alternative solutions :)

**Comment by crookedneighbor** [comment]
Seems reasonable to me.

**Comment by AlbinoDrought** [comment]
I'm not sure what consequences it would have, but something like this seems to work well for my usecase:
https://github.com/AlbinoDrought/braintree-web-drop-in/tree/please-click-the-paypal-button-thanks

Enabling the "Pay" button on the demo like this: 
http://localhost:4567/?disablePaymentMethodRequestableListeners=true

and then clicking PayPal and clicking "Pay":

![image](https://user-images.githubusercontent.com/852873/45902180-96f43480-bd9a-11e8-897a-cf369af380cd.png)

**Comment by SampsonCrowley** [comment]
@crookedneighbor is there any way to remove the need to click the button twice? Either through removing the first button and showing the actual paypal button straight off the bat, or simulating a click on the actual paypal button when the selector button is clicked?

**Comment by crookedneighbor** [comment]
You can utilize the events API: https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#on

See the example `Automatically submit nonce to server as soon as it becomes available`

**Comment by AlbinoDrought** [comment]
If I'm picking up what you're putting down @SampsonCrowley (when shown the list of addable payment methods, clicking "PayPal" would automatically jump to the PayPal auth/payment flow instead of showing the "inner button"), I'm not sure if this would be possible without replacing the initial menu item with the actual checkout.js button.

There's some talk about programmatically triggering the PayPal flow in this thread and how it is not and will not be supported: https://github.com/paypal/paypal-checkout/issues/512#issuecomment-339508532

**Comment by SampsonCrowley** [comment]
@crookedneighbor, yeah I'm aware of that limitation. But it it possible to never show the first button that users currently have to click? so that the first time a user clicks the "paypal" button it IS the direct user interaction to open the paypal checkout form?

I'm positive EVERY client using any of our checkout forms would be happier to just click the paypal button the first time, instead of there being a button to show the paypal button

**Comment by crookedneighbor** [comment]
@SampsonCrowley I agree that it would be better to reduce the clicks, but PayPal doesn't allow anyone to trigger the PayPal checkout flow outside of clicking the PayPal button. Here's a mockup of how it would look to accomplish that within the payment method option view:

<img width="540" alt="screen shot 2018-10-11 at 9 08 59 am" src="https://user-images.githubusercontent.com/2916945/46809987-54889c80-cd35-11e8-8f9c-2d97aba7fc64.png">

There's a few of product design problems with this:

A) It's confusing to have one option be a selector and another to be a direct button
B) It's unclear if the customer should be clicking the PayPal logo or the PayPal button or the overall container (and again, it will only work to click the button, no other way to trigger it)

There are other ways to handle it, like having the selector be a radio button similar to the ["mark" integration flow example on the PayPal docs](https://developer.paypal.com/demo/checkout/#/pattern/mark). But that would require a complete redesign and be a major version bump.

So, at this time, we're not going to change the design of Drop-in.

However, Drop-in is just a pre-made integration with version 3 of [braintree-web](https://github.com/braintree/braintree-web), so if this is something your site requires, you can always fork the repo and make the changes yourself. See https://github.com/braintree/braintree-web-drop-in#customization for details.

Since this is getting waaaaaaay off topic from the original issue, if you have further concerns about it, please open a new issue.

**Comment by crookedneighbor** [comment]
Fixed in 1.16.0

**Comment by dan003400** [comment]
I love when I find PayPal used across the web, it is implemented 100 different ways.

Every iteration of the SDK adds more friction to the customer experience and makes the developer experience worse... seems backwards to me.
