### ISSUE TITLE
Green checkmark works correctly default card don't change on click

### ISSUE THREAD

**Issue by andylacko** [braintree/braintree-web-drop-in#434]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox/Production
* Browser and OS 

### Issue description

Hello,
I don't know, if it's bug or feature, but when I select card from more cards, green checkbox is checked, but then I refresh page and old preselected card is active. How to achieve select the card by clicking on it?

It is pretty straight forward UX element and if nothing happens, user is 100% sure confused. We are about to invest time to building our own component, but then asking why? Shouldn't be drop-in component doing what we desire?

Hope there is solution for this

**Comment by andylaci** [comment]
@crookedneighbor , but now when the dropin element is loaded, I see something like this:

![image](https://user-images.githubusercontent.com/7139923/46617253-968ac600-cb1c-11e8-804b-efcc38609657.png)

but I wanted the "used" payment method to be checked, and the when user decides to change it, it will rerender

my code looks something like this:
```
braintree.dropin.create({
          authorization: this.state.clientToken,
          selector: '#dropinContainer',
          vaultManager: true,
          preselectVaultedPaymentMethod: false,
        }, (err, dropinInstance) => {
          if (err) {
            // Handle any errors that might've occurred when creating Drop-in
            console.error(err)
            return;
          }
          submitButton.addEventListener('click', (e) => {
            e.preventDefault()
            dropinInstance.requestPaymentMethod((err, payload) => {
              if (err) {
                alert('there was some mistake in connection when trying to add card, please try again one more time')
              }
              self.addCard(payload.nonce)
            })
          })

          dropinInstance.on('paymentMethodRequestable', (event)=> {
            if (event.paymentMethodIsSelected) {
              dropinInstance.requestPaymentMethod((err, payload) => {
                if (err) {
                  alert('there was some mistake in connection when trying to add card, please try again one more time')
                }
                self.addCard(payload.nonce)
              })
            }
          })
        })
```

**Comment by crookedneighbor** [comment]
I don't think I fully understand what you are trying to do. Can you walk me through it in more detail?

When you load drop-in with a client token that includes a customer id, it will load the customer's saved payment methods and have the one that is their default payment method checked. (unless you have `preselectVaultedPaymentMethod: false` in your create config, in which none will be checked)

Clicking on a saved payment method makes no changes to the customer object, so it's not surprising that when refreshing the old payment method is selected, because it is still the one marked as the default.

An action must be taken using a server side SDK to update the customer's default payment method. https://developers.braintreepayments.com/reference/request/customer/update/#default_payment_method_token

**Comment by andylaci** [comment]
Hello, now I created code that looks something like this:

```javascript
      const methods = document.getElementsByClassName('braintree-method')
      Array.from(methods).forEach((element) => {
        element.addEventListener('click', () => {
          dropinInstance.requestPaymentMethod((err, payload) => {
            if (err) {
              alert('there was some mistake in connection when trying to add card, please try again one more time')
            }
            console.log(payload)
            // self.updateCard(payload.nonce)
          })
        })
      })
```

but how do I receive card token, in JSON object I only receive nonce, can I somehow search that token server side? How do I recognize which card was selected in data way? 

```php
result = gateway.customer.update(
  "a_customer_id",
  :default_payment_method_token => "the_token"
)
```

**Comment by crookedneighbor** [comment]
We're working on a solution to better convert the payment method nonce to the vaulted payment method it refers to.

As a workaround though, you can use [gateway.payment_method.create](https://developers.braintreepayments.com/reference/request/payment-method/create/ruby). When you pass in a payment method nonce that represents a vaulted payment method to `create`, it will instead return the vaulted payment method instead of creating a new payment method.

Once you have that, you can pass the [token](https://developers.braintreepayments.com/reference/response/payment-method/ruby#token) into the `:default_payment_method_token` param.

**Comment by simeyla** [comment]
@crookedneighbor The concept of a 'default' payment method needs to be better explained in the drop-in docs. There is no mention whatsoever of a 'default payment method' in this doc https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html

I've learnt by now (in general - not just with you guys) to go to github issues first when researching an issue, and your comments above are very helpful. Would be great to get the docs updated with this information so it isn't buried here.

It's very important to me for the customer to have their default payment method selected - so if they come back to make a purchase I can preselect the *previous* payment they used. Otherwise I'm sure we will get people saying 'You charged my PayPal account but I don't use it anymore' - or something like that.

A configurable option to automatically set 'default payment method' when a successful payment is made would be great too, but I can just do what you suggested above (unless this new solution you talk about is now available). 99% of the time I'd want the *default* method to be the *previous* one they last used successfully.
