### ISSUE TITLE
PaymentMethodRequestable not working with credit cards

### ISSUE THREAD

**Issue by ProductOfAmerica** [braintree/braintree-web-drop-in#457]
### General information

* SDK/Library version: 1.2.3
* Environment: Sandbox
* Browser and OS: Chrome 56.0.2924.87 (64-bit) on Windows 10

The gif should show the issue. Basically, even when I enter valid info into the pane, `paymentMethodIsSelected` is `false` even after all the correct fields are filled in.

![2018-11-22_15-22-02](https://user-images.githubusercontent.com/14712114/48922202-b119c400-ee6a-11e8-8c33-9633d1d1ba33.gif)

**Comment by crookedneighbor** [comment]
This is expected behavior. There's some nuance here.

The `paymentOptionSelected` event fires when a payment option is clicked. You see this when you log `onPaymentOptionSelected`

The payload from the `paymentMethodRequestable` includes a `paymentMethodIsSelected` value, which is different from a payment option. In payment methods such as PayPal or Apple/Google Pay, the end result is a view where the payment method is selected and immediately retrievable. In the case of form based payment methods, like credit cards, the form is requestable, but it is not already selected. Hence `paymentMethodIsSelected === false`. 

If the credit card was a vaulted payment method and it was selected (or if the customer tokenizes their card, switches to another payment method option and then switches back to the card), the value of `paymentMethodIsSelected` would be `true`.

The `paymentMethodIsSelected` field is intended to indicate if the payment method is in a terminal state and will succeed definitely when requested. This is to prevent the customer to need to click an additional time to finish their checkout after completing the flow (PayPal, Apple Pay, Google Pay, etc).

If the field is `false`, this indicates that it's possible that the payment method could be requested, but in the case of credit cards, this will require a tokenization request, which may fail. In addition, if you have postal code verification turned on, the event will fire after 3 digits are entered (as that is a valid postal code length in Iceland). So it's not reliable to automatically request it once the event fires. 

The normal flow would be to enable a buy button once the event fires, and disable it if `noPaymentMethodRequestable` is fired. This gives the customer a chance to review their information and confirm it before attempting to tokenize the credit card.

With your flow, since no postal codes are present in the form, you could safely ignore the `paymentMethodIsSelected` value and request the payment method automatically. (although, I'd still recommend letting your customers confirm their credit card information instead of doing it automatically) However, if you ever add postal code to your AVS rules or a new form based payment method is added to Drop-in, you will want to change your integration.

**Comment by simeyla** [comment]
> The paymentOptionSelected event fires when a payment option is clicked. 

@crookedneighbor So how do I find out which option is selected when `preselectVaultedPaymentMethod: true`? 

I may want to show or hide certain parts of UI underneath the dropin form - based on whether or not a payment method is already selected. I don't see any way to do so unless I access private properties on the braintree 'instance'.

**Comment by ProductOfAmerica** [comment]
@crookedneighbor thanks for the reply, didn’t see it till now for some reason.

Just to clarify: the best workflow is to enable a `buy` button once the `paymentMethodIsSelected` fires regardless of its contents?

**Comment by crookedneighbor** [comment]
@ProductOfAmerica No. You should enable and the `buy` button when `paymentMethodRequestable` is fired and disable it when `noPaymentMethodRequestable` event is fired.

If you wanted to bypass requiring the customer to press the `buy` button altogether, for payment methods like PayPal, you are safe to call `requestPaymentMethod` when the `paymentMethodRequestable` event fires and `paymentMethodIsSelected` is true.

See the examples here: https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#on

@simeyla There's an `isPaymentMethodRequestable` method on the instance that you can call as soon as the setup is complete. If it returns `true`, you can call `requestPaymentMethod` and inspect the payload to update your UI.

```js
var submitButton = document.querySelector('#submit-button');

braintree.dropin.create({
  authorization: 'CLIENT_AUTHORIZATION',
  container: '#dropin-container'
}, function (err, dropinInstance) {
  if (dropinInstance.isPaymentMethodRequestable()) {
    // This will be true if you generated the client token
    // with a customer ID and there is a saved payment method
    // available to tokenize with that customer already selected
    dropinInstance.requestPaymentMethod(function (err, payload) {
      // inspect payload.type to update your UI
    });
  }
  // ...
```
