### ISSUE TITLE
3DS 2.0 Support

### ISSUE THREAD

**Issue by tyrbuvladislav** [braintree/braintree-web-drop-in#480]
Will Drop in support 3DS 2.0?
https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3?utm_campaign=BT_EMEA_Ops_3DSPSD2_2_20190219&utm_medium=email&utm_source=Eloqua&elq_cid=5220208

**Comment by crookedneighbor** [comment]
Yes, once the 3ds 2.0 work is out of beta, it will be added to Drop-in.

**Comment by tyrbuvladislav** [comment]
Cool, thx ;)

**Comment by jiripospisil** [comment]
@crookedneighbor Hello, is there any update on this? ETA? Thank you.

**Comment by hollabaq86** [comment]
Hi @jiripospisil, we don't have a timeline yet, but we'll update this issue as soon as we do!

**Comment by precheur007** [comment]
Hi ! Do you have a date for an update on this issue please ? Thanks a lot.

**Comment by hollabaq86** [comment]
Hi @precheur007, no updates yet. Once 3DS 2.0 is out of beta, it will be added to the Drop-In.

**Comment by peterlozano** [comment]
Deadline is coming..... September 14th all European merchants need to be PS2 compliant and that's achieved using 3D Secure 2.0.

I hope those Braintree guys know what they are doing ;)

**Comment by hithomasmorelli** [comment]
Got an email today saying that 3DS 2.0 SDKs are now available in production. Still in beta though it seems...
@hollabaq86 @crookedneighbor any ETA on 3DS 2.0 for Drop-in would be greatly appreciated. Despite the Braintree emails urging me to update my site to use 3DS 2.0, I can't change anything until it's released for Drop-in.

**Comment by hollabaq86** [comment]
🙋while our client SDKs are still in development, the functionality to perform authentications on the 2.0 rails is production ready. 

We understand that everyone watching this issue is anxious to add support for 3DS 2.0 to their Drop-In integration. We're anxious to get it to you, too!

We're actively working on getting 3DS 2.0 out of beta for the client SDKs, and we'll update this issue when we have meaningful updates to the Drop-In library. In the meantime, [here's a codepen](https://codepen.io/braintree/pen/KjWqGx) showing how you can incorporate the current braintree-web 3DS 2.0 beta version into the Drop-In.

**Comment by hithomasmorelli** [comment]
@hollabaq86 thanks!
I assume that the codepen example is also production ready, am I correct or not?

**Comment by crookedneighbor** [comment]
The codepen is provided as a sample. You'll want to do the following to make it production ready:

a) provide your own validations on the billing address inputs, all the example does is check that they are not empty
b) remove the autofill button and test data table. No reason to have your customers fill in fake data for the form!
c) replace the client token generation with a client token from your own server. How you do that is up to you. (whether it calls out to an external server like the example, or is embedded onto the page, or whatever)

The SDK itself is production ready, but it is still a beta, so if a new beta is released, or it goes to General Availability, you will need to review the documentation for any breaking changes with the new release. (after it is released to GA, there will be no breaking changes)

**Comment by riccardomessineo** [comment]
Should we expect the integration of 3D Secure 2.0 on the standalone version of DropIn UI (as it is for the supported 1.0 version) or will additional scripts have to be added and configured as you did in the codepen?

**Comment by crookedneighbor** [comment]
@riccardomessineo Once the underlying sdk (which drop-in uses) is out of beta, Drop-in will be updated to use 2.0. No additional scripts will be needed by the developer to integrate.

**Comment by raRaRa** [comment]
It seems like it's now supported in version 3.47.0 of `braintree-web`. Ref: https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md

**Comment by hollabaq86** [comment]
@raRaRa yes it is 😃 3DS 2.0 Support for Drop-In is currently under development. 

We currently do not have an ETA on when it will be released, but we know this is a priority for our merchants ❤️ we'll update this issue when we have more news.

**Comment by lucasRolff** [comment]
@hollabaq86 hopefully before september right? :-D

**Comment by crookedneighbor** [comment]
Got a PR out for some basic functionality: https://github.com/braintree/braintree-web-drop-in/pull/523

**Comment by hollabaq86** [comment]
🎉 [Version 1.19.0](https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#1190) includes support for 3DS 2.0 🎉 . We're going to go ahead and close this issue- if you have any feedback (bugs/improvements), please feel free to create a new issue!

**Comment by crookedneighbor** [comment]
I've updated the codepen to use 3DS 2 built into Drop-in: https://codepen.io/braintree/pen/KjWqGx

A future update will have the ability to collect the customer information needed for 3DS 2 within Drop-in itself, but this release as is should give y'all a good start.

**Comment by lucasRolff** [comment]
@crookedneighbor - trying your codepen (and having integrated 3DS 2.0 myself), the test cards provided doesn't actually trigger a liability shift, additionally the `1091` card doesn't trigger a challenge, and neither does the `1109` card.

Even if putting the expiration date exactly 3 years in the future (07/22), it still doesn't do the liability shift or gives a challenge - making it hard to test if the integration *actually* works :(

**Comment by crookedneighbor** [comment]
@lucasRolff All of them worked just fine for me just now. I'd contact our support team so we can figure out why it doesn't work for you.

https://help.braintreepayments.com/

**Comment by lucasRolff** [comment]
@crookedneighbor ![https://snaps.hcdn.dk/hjavEUEzkEWeZID4WDCIUrTw2oNX3b8XHAeDdDbmPQ.png](https://snaps.hcdn.dk/hjavEUEzkEWeZID4WDCIUrTw2oNX3b8XHAeDdDbmPQ.png)

I don't think asking support why the codepen demo doesn't work, will solve anything :) the tested card (as you see in the above screenshot) is the 1091 one, and says `liabilityShifted: false`, additionally, no challenge was ever issued.

So maybe it just doesn't work from Europe 🤷‍♂ 

Testing using the older cards such as `4000000000000002` `01/2020` will reveal the challenge for example.

I find it weird the demo doesn't demonstrate a challenge with the supplied cards assuming the demo is indeed correct - that would only point towards the numbers being incorrect, since a liabilityshift never actually happens.

**Comment by lucasRolff** [comment]
I found the problem - the 3DS 2.0 challenge will never show if people use adblocker such as uBlock Origin.

**Comment by crookedneighbor** [comment]
We're aware of this issue and have escalated it to Cardinal.

**Comment by gbwashleybrown** [comment]
I have followed the Codepen example and I have that working great for singular payments. What I'm unsure on is how do we handle subscriptions/recurring payments? 

The Braintree official documentation recommends we trigger a cardholder challenge by passing `challengeRequested: true` on the `verifyCard()` call but the `verifyCard()` call isn't used in the codepen example above?

**Comment by crookedneighbor** [comment]
Where do you see `challengeRequested: true` in the docs? That's not an option for the raw sdk.

As far as your actual question goes, it should automatically run the vaulted nonce through the 3ds flow: https://github.com/braintree/braintree-web-drop-in/blob/cdcf21a5618c984559a7b394964b274d4446d705/src/dropin.js#L694

It'll trigger that flow if you have 3ds configured in drop-in, if it's a credit card (vaulted or not) and there is not already liability shift info on the nonce.

**Comment by gbwashleybrown** [comment]
@crookedneighbor I should have probably expanded on my initial question to say that when following the JS V3 documentation (since dropin for 3DS2 docs aren't officially released yet), it recommends that you trigger a cardholder challenge as stated here: 


## Recurring transactions
https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3#recurring-transactions
> The recommended flow for recurring billing would be to *request a cardholder challenge* to establish SCA when the card is first authorized as part of storing it to the Braintree vault. This can be with a verification, or the first transaction of a recurring billing event. By applying 3D Secure to the first transaction or verification, you signal to the card issuer that you have established a mandate between you and your customer to charge their payment method for subsequent recurring payments as detailed in your terms and conditions. Such subsequent transactions are exempt from PSD2 SCA requirements.
> 
> Establishing SCA on verifications will be useful for scenarios where the cardholder will not be present when the charge is issued, and the amount isn’t known when the payment method is stored. For example, if you have a metered billing flow and invoice customers at the end of a month based on their usage, you can use 3D Secure on your initial card verification to establish a mandate to create future merchant initiated transactions (MIT).



## Requesting a cardholder challenge
https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3#requesting-a-cardholder-challenge
>To override the default behavior of 3DS 2 and request the cardholder's bank to issue an authentication challenge, pass `challengeRequested: true` on the `verifyCard()` call.

I was just assuming that we would have to do the following somehow, even with the dropin ui. But in regards to: 

> As far as your actual question goes, it should automatically run the vaulted nonce through the 3ds flow:

Considering the above recommends we override the default behavior and force an auth challenge, how would the dropin ui know to do that? Forgive my ignorance, perhaps I'm just not understanding this correctly. I'm fairly new to working with Braintree.

**Comment by crookedneighbor** [comment]
Ahh yes, I remember that param now. I had forgotten it was added. You should just be able to include it in the `threeDSecure` options in the `create` options or the `threeDSecure` options in `requestPaymentMethod`.

**Comment by crookedneighbor** [comment]
I was wrong about the `create` options, but it will work when passing in the `threeDSecure` options to `requestPaymentMethod`

https://github.com/braintree/braintree-web-drop-in/blob/9942c735e21d4adf14ddde617fd82764cd1dfb82/src/lib/three-d-secure.js#L23-L34

**Comment by vlastimil-dolejs** [comment]
I have a problem with the provided Codepen example. If I fill in "Billing given name" field with non-ascii characters (for example: Šimon). The submit request returns `422 Unprocessable Entity`: `{"error":{"message":"Billing given name format is invalid."},"threeDSecureInfo":{"liabilityShifted":false,"liabilityShiftPossible":false}}`

It seems that there are some restrictions not mentioned in the [docs](https://braintree.github.io/braintree-web/3.47.0/ThreeDSecure.html#~billingAddress)?

**Comment by crookedneighbor** [comment]
@vlastimil-dolejs We'll get the docs updated to include that limitation.

This original issue was about when 3ds 2.0 would be added to drop-in. Since that has happened, I'm going to lock this issue. Fo any future 3ds 2.0 concerns, create a new issue.
