### ISSUE TITLE
Drop-in doesn't prompt for Street Address if AVS Rules settings require it

### ISSUE THREAD

**Issue by cwilso03** [braintree/braintree-web-drop-in#486]
### General information

* SDK/Library version: 1.16.0
* Environment: production
* Browser and OS: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
### Issue description

If I enable the various "Street Address" AVS rules in my Braintree production environment, they are enforced by the back-end API.  However, the web drop-in component does not show a field for street address, like it does for zip code (if the "Postal Code" AVS rules are enabled).

**Comment by crookedneighbor** [comment]
Hi @cwilso03, this is something we're actively working on adding. We'll update here when it's ready.

Are you being prevented from tokenizing? Or just transacting with the nonce? If just transacting, you should be able to collect the billing details outside of Drop-in and send them along in the `transaction.sale` call.

In the future, this will be enabled as part of Drop-in's flow and the billing details will be captured in the nonce.

**Comment by cwilso03** [comment]
Hi @crookedneighbor, thanks for the quick reply.  At the present time, I'm just transacting with the nonce.  I agree; I can simply collect the street address info separately to send along.  I opened the issue since there didn't seem to be one already in the list, as I figured you'd want consistency with how postal codes are handled.

**Comment by crookedneighbor** [comment]
We won't be able to do it automatically like postal code and cvv work, because it'll be highly possible that the merchant is already collecting the billing information outside of Drop-in, and presenting it twice would not be ideal and could constitute a breaking change. So when it does get added, it'll have to be opt-in.

We can explore either making it auto-populate in the next major version, or make configuring CVV and Postal Code explicit rather than implicit.

Thanks for opening the issue, it helps us track interest in features like this.

**Comment by chanachai285** [comment]
https://github.com/chanachai285/-

**Comment by januszm** [comment]
I am also interested in adding the street address field to the drop-in. I came here to this GH issue page because after enabling the AVS option "Street Address not provided (I)", Drop-In did not display the address field and the transaction could not be completed. In the project I'm working on, a small percentage of transactions are rejected by banks because of the missing address and postal code fields. This address does not always have to match the address that is stored in the Merchant system. Enabling the Postal code option won't solve the problem, it should be both Postal code and Street Address I think.

**Comment by januszm** [comment]
To sum up, the currently recommended solution is to add your own "street address" form field, e.g. just below the drop-in code, and send it with the rest of the data to the server?

**Comment by crookedneighbor** [comment]
Yes, that is the recommended solution at this time. Providing street address collection within drop-in is on our roadmap, but not ready quite yet.

**Comment by jhillyerd** [comment]
It's been three years, how's that roadmap looking?

**Comment by hollabaq86** [comment]
👋 hey folks, going to close this issue as it's a feature request and not a 🐛, but it'll stay at the top of our repo's issues since it's pinned for future folks to find.

I don't have an ETA on if/when we'll add this to the Drop-In or when we'll have any updates. But this request has been registered with the right folks to get evaluated and prioritized. We're a small team with a big codebase to manage 😅 so we're doing our best to work through some of our outstanding requests (like the fact that it's been three years and we still don't have an answer for y'all!).

for internal tracking, issue 3213
