### ISSUE TITLE
Add card alias / nickname / label?

### ISSUE THREAD

**Issue by sbull** [braintree/braintree-web-drop-in#498]
### General information

* SDK/Library version: 1.17.2
* Environment: Production
* Browser and OS: Any / Chrome 72.0.3626.121 on Windows 10

### Issue description

Feature request:

As a user who is part of corporate account (having one Braintree "Customer ID" for the entire company, to share payment methods), I want to label my saved payment methods so that I know which one I ought to use.

My Braintree integration allows "corporate" accounts to save payment methods, and these are shared amongst the users under the corporate account. Different cards are used for different regions, based on who/where they're ordering something for. It would be great if the users could give the stored cards labels/nicknames, so that it's easier for them to associate which card to use at any given time.

It could suffice to put the UI behind the vault "Edit" feature, which I think currently only allows deletion of existing cards.

Here's a picture of wondering which card to pick.

![image](https://user-images.githubusercontent.com/1115369/56406150-d7c70580-6224-11e9-821a-42f10f855f23.png)

**Comment by quinnjn** [comment]
It seems like an interesting suggestion, but I don't think we would want to implement this because it further identifies the card. I'm thinking of a problem where a customer decides to label their card as their full card number, name, address, etc.

There is some identification with the saved cards, the last4 digits. Your problem could be solved with a simple browser extension that maps the last 4 to a label you have defined in that extension.

**Comment by sbull** [comment]
I'm wondering if it might be possible to alleviate your objection to this by restricting the label to disallow digits (or allow only alphabetic characters).

On many sites where I store my card for future use, I am encouraged to give my card a nickname. I was hoping that the Braintree Drop-in UI would be able to provide similar functionality at some point.
