### ISSUE TITLE
No event when switching between requestable payment methods

### ISSUE THREAD

**Issue by wagonli** [braintree/braintree-web-drop-in#499]
### General information

* SDK/Library version: 1.17.2
* Environment: sandbox
* Browser and OS Firefox 66.0.3, Fedora 29

### Issue description
No paymentMethodRequestable event is thrown when switching from a valid creditcard form to a saved payment method.

This may not exactly be an issue as there is not a change in the dropin state (we're transitioning from a requestablePaymentMethod to the same state).
But I feel this pose an issue : 
- all your example promote to request automatically the paymentMethod when the user selects a saved payment method (locally or vaulted)
- without a proper event that notify a switch of the payment method, we cannot apply that automatic process because we cannot know if the user is still on it's manually entered payment method or on a previously saved one.
- So we have to display either way a button for the user to manually trigger the paymentMethod request.

**Comment by demerino** [comment]
@wagonli Thanks for raising this concern. To be clear, you'd like to know when a customer is changing between valid payment methods in Drop-in?

**Comment by wagonli** [comment]
Yes that would be very useful in order to ease some user interactions.

**Comment by Simanas** [comment]
Trying to implement braintree payments in to my website for the first time for last few days and it is ether I do not understand or missing something, or you guys are missing something... :)

I followed your installation instructions and all the docs... So in order to make a sale I need to provide payment_method_nonce which is obtained by calling dropinInstance.requestPaymentMethod(), I do this by hooking to an event of requestablePaymentMethod. So what I expect to happen is to get that payment_method_nonce every time user switches to a different method. Well.. turns out I am wrong! This is only fired when new payment method is added. If user changes between his previously used cards this event is not being fired. I have read all the docs and this issue... It turns out that there is no way at all of knowing when user selects his other payment methods. So please educate me on how should I get correct payment_method_nonce if this is not working as it obviously should? 

Here is how my payment page looks like:

![Screenshot from 2019-08-14 19-15-04](https://user-images.githubusercontent.com/2435008/63038436-d7383600-bec9-11e9-868d-d9442e6eb129.png)

I select second card to pay with. But all the transactions that I receive are from first card:

![transactions](https://user-images.githubusercontent.com/2435008/63038495-f8008b80-bec9-11e9-8e02-d22721cc6503.png)

Well.. yes... I will prevent my own payment form from submission, call dropinInstance.requestPaymentMethod() and only then submit the form. But it's just a stupid workaround to the problem that should not even existed at first place. 

Please fix this or provide other simple convenient event handler which would fire every time user get's his payment method selected.

**Comment by crookedneighbor** [comment]
This will be out in the next version. Will update here when it is available.

**Comment by crookedneighbor** [comment]
This is out in v1.22.1
