### ISSUE TITLE
Undocumented changes impacting Content Security Policy

### ISSUE THREAD

**Issue by wagonli** [braintree/braintree-web-drop-in#534]
### General information

* SDK/Library version: drop-in 1.19
* Environment: Sandbox (and production ?)
* Browser and OS Firefox / Fedora 29

### Issue description

We implemented a strict CSP policy when starting with drop-in 1.18, following documentation here : https://braintree.github.io/braintree-web-drop-in/docs/current/#content-security-policy

With drop-in 1.19 and 3D Secure 2.0 we have some CSP errors due to call to scripts hosted at undocumented URLs (not limited to) :
- *.cardinalcommerce.com
- https://includestest.ccdc02.com/cardinalcruise/v1/83a3dc284ae5fa04311c/5.83a3dc284ae5fa04311c.songbird.js 

We're not really confident to do a trial and errors to find all CSP rules to add against sandbox and prod so an updated list would be really useful.

**Comment by crookedneighbor** [comment]
Sorry about this, we'll get the doc fixed up.

**Comment by crookedneighbor** [comment]
This will go out in the next release. Also, we updated the version of the Cardinal SDK and it (supposedly) eliminates the `ccdc02.com` domain.

**Comment by crookedneighbor** [comment]
Content security policy is updated. `*.cardinalcommerce.com` should be the only cardinal domain that the SDK uses now.

**Comment by Mneroen** [comment]
For the 3D Secure iframe i had to enable more URIs in my Content Security Policy.

https://songbird.cardinalcommerce.com/edge/v1/91ae5edca378ad3af82e/11.91ae5edca378ad3af82e.songbird.js calling these URIs for the 3D Secure iframe:

- www.clicksafe.lloydstsb.com
- pay.activa-card.com
- 3dsecure-1.wirecard.com
- acssv.otpbank.hu
- acs.sia.eu
- idcheck.acs.touchtechpayments.com

Are there any more?
Are these URI's country specific? Like the otpbank.hu for Hungary or the lloydstsb.com for United Kingdom customers?

**Comment by SecureExchanges** [comment]
What are the CSP for dropin control ? Is it possible to get an updated revision of the CSP ?

I get a couple of error when we trying to use the dropin 1.33.0 version

Refused to connect to 'https://centinelapi.cardinalcommerce.com/V1/Order/JWT/Init' because it violates the following Content Security Policy directive: "connect-src"

Refused to connect to 'https://kg668dbov0.execute-api.us-east-1.amazonaws.com/prod/log' because it violates the following Content Security Policy directive: "connect-src"

Our CSP are based on that
![image](https://user-images.githubusercontent.com/38925527/156438803-acef8354-27e8-4be5-8389-79eccbecacc7.png)
