### ISSUE TITLE
Passing CSS class name for override throws error

### ISSUE THREAD

**Issue by thatsnotright** [braintree/braintree-web-drop-in#535]
### General information

* SDK/Library version: 1.19.0
* Environment: sandbox
* Browser and OS Chrome 75 / Linux

### Issue description

According to the hosted fields [documentation](https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~styleOptions) (which this plugin refers to for styling help) I should be able to pass a CSS class name for a style override, such as:

```javascript
dropin.create({
      authorization: context.braintreeAuthorizationKey,  
      container: '#braintree-dropin-container',  
      card: {  
        overrides: {  
          styles: {  
            'number': 'TextInput',  
          },  
          fields: {  
            number: {maskInput: {showLastFour: true}},  
            cvv: {maskInput: true},  
          },  
        },  
      },  
    }, (createErr, instance) => { });  
```

However when I try this I receive the following exception:
`Cannot assign to read only property '0' of string 'TextInput'
    at https://localhost:3000/webpack/app.js:35704:32
    at Array.forEach (<anonymous>)
    at normalizeStyles (https://localhost:3000/webpack/app.js:35701:23)
    at https://localhost:3000/webpack/app.js:35285:7
    at Array.forEach (<anonymous>)
    at CardView._generateHostedFieldsOptions (https://localhost:3000/webpack/app.js:35278:35)
    at CardView.initialize (https://localhost:3000/webpack/app.js:35069:20)`

Is this functionality intended to be supported?

Am I misunderstanding the hosted field documentation?

**Comment by crookedneighbor** [comment]
Ahh, Drop-in doesn't account for `styles` being a string instead of an object when you pass an override: 

https://github.com/braintree/braintree-web-drop-in/blob/d952a71c5006549be8ab492980db04175eaead8b/src/views/payment-sheet-views/card-view.js#L239-L255

https://github.com/braintree/braintree-web-drop-in/blob/d952a71c5006549be8ab492980db04175eaead8b/src/views/payment-sheet-views/card-view.js#L662-L668

We'll need to do a check if the type of the individual style is a string and just use that if it is. Feel free to open a PR if you'd like to get a start on it, otherwise, we'll add it to our backlog.

**Comment by crookedneighbor** [comment]
This will go out in the next release. Gonna re-open the issue until then.

**Comment by crookedneighbor** [comment]
This is out now in  v1.20.2
