### ISSUE TITLE
HOSTED_FIELDS_TIMEOUT; braintree inside iframe and shadow DOM

### ISSUE THREAD

**Issue by phips28** [braintree/braintree-web-drop-in#614]
### General information

* SDK/Library version: v1.16.1 & v1.22.1
* Environment: Production
* Browser and OS Chrome Version 80.0.3987.163 (Official Build) (64-bit)

### Issue description

We host an iframe with the checkout process inside a shadow DOM.  But it fails with the following Error: `{name: "BraintreeError", code: "HOSTED_FIELDS_TIMEOUT", message: "Hosted Fields timed out when attempting to set up.", type: "UNKNOWN", details: undefined}`

Our DOM structure:

- `html`
  - `body`
  - ...
  - `shadow root`
     - ...
     - iframe (`<iframe src="https://webviews.dock.bot/qe/address?placeId=5e79f33fbc72b5c3ace13294&&source=QE&&rate=45&&itemName=Bug Out Bag" sandbox="allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-top-navigation" allowfullscreen="" width="100%" height="100%" data-openedfrombotcopy="true"></iframe>`) - website with react and braintree-web-drop-in
        - `div.braintree-dropin-react`
           - `div.braintree-dropin-react-form`

I have read through the code (braintree-web-drop-in & braintree-web), and found that iframe stuff. But I dont understand why you need to access the parent if the checkout is hosted within the iframe.

When using the iframe without the wrapping shadow DOM everything works. (But I cant change this because we are using another plugin that creates the shadow DOM)

---

Related issue: https://github.com/braintree/braintree-web-drop-in/issues/296

But that workaround doesnt work for us, as we use another plugin that creates the shadow DOM. 

Any other idea how to fix this?

**Comment by gesa** [comment]
Hey @phips28. It's not clear to me what you meant in a few different places. What were you referring to when you mentioned "that iframe stuff"?

There are a lot of variables here that may be compounding issues. We've seen issues in the past with nested iframes that have sandboxing applied. If the drop-in is being initialized inside an iframe that is a fully-formed document, I wouldn't _expect_ the shadow dom to be the issue. Can you provide a simplified example of this problem being triggered?

**Comment by phips28** [comment]
@gesa hello, thx for your response.

Here is a video of the issue https://www.dropbox.com/s/o05r4nw79rag4cd/quarantine%20%281%29.mp4?dl=0

And here the steps to reproduce -> 
1. Open https://quarantineemergency.com/
2. Select "Bug out Bag" option
3. Select "Buy Now!"
4. Fill the form with basic details (Can put dummy details but original mobile number of US)
5. Put the 4 digit received pass code on your registered mobile number.
6. You will be redirected to payment page. Here you will get error after few seconds

there you can see the DOM structure as described above.
the iframe inside shadow DOM holds the page with the braintree plugin.
`<iframe src="https://webviews.dock.bot/qe/address?placeId=5e79f33fbc72b5c3ace13294&&source=QE&&rate=45&&itemName=Bug Out Bag" sandbox="allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-top-navigation" allowfullscreen="" width="100%" height="100%" data-openedfrombotcopy="true"></iframe>`

**Comment by crookedneighbor** [comment]
👋 The hosted fields iframes need access to each of the frames on the parent window so they can easily sync up the checkout form data between the various frames. In a standard DOM environment, this works without a problem. The iframe can access all the other iframes on the parent window that share the same domain with it. Within the shadow DOM, the iframe does not get access to those sibling frames.

We're looking to address this on the SDK level, but there's no set timeline for it.

**Comment by FullstackJack** [comment]
Well, this is blocking me from building an iframe'd checkout on Flutter Web because the iframe ends up in a shadow DOM and I don't see another API method in your Client SDK that allows me to pass form data to your servers.

**Comment by crookedneighbor** [comment]
We've made progress in the underlying sdk to solve this: https://github.com/braintree/braintree-web/issues/495#issuecomment-662063359

We have a beta out of the core sdk (see the comment on that issue), if you'd like to try integrating with Hosted Fields directly instead of through Drop-in.

There are some additional challenges to having full shadow dom support in Drop-in (not sure if all the other payment methods Drop-in provides can support it right now), but hopefully the Hosted Fields bit will be solved once the core sdk is released and Drop-in is updated to use that new version.

**Comment by crookedneighbor** [comment]
Got an initial PR out for this for the card payments portion of Drop-in: https://github.com/braintree/braintree-web-drop-in/pull/647

@phips28 @FullstackJack  @jbuckner

What payment methods do you need to support? I'd like to prioritize the ones y'all use since y'all have been the ones to ask for this. Some (such as PayPal) just won't work until we're able to upgrade to the latest PayPal SDK (which can't happen without a Drop-in major version bump), but I'm hopeful that we can get the other ones to work in the near future.

**Comment by crookedneighbor** [comment]
This should work now with the card view in v1.24.0.

Other payment methods will likely not work at this time. Going to close this for now, but we'll be adding support as we can for the shadow DOM for other payment methods as part of the work for version 2 of Drop-in.
