### ISSUE TITLE
Clearing all form fields programatically

### ISSUE THREAD

**Issue by giedrius-timinskis** [braintree/braintree-web-drop-in#621]
### General information

* SDK/Library version: 1.22.1 
* Environment: Not relevant
* Browser and OS: Not relevant

### Issue description
Hi!
First of all, I wanted to thank you for developing this library. It's been a delight to use so far.

I have a question about a use case I have. I'd like to clear the credit card payment fields in case of a 'soft' error (e.g. insufficient funds response). Is there a way to clear the fields via the dropin instance somehow? Something like `braintreeDropin.clear()` would be very useful.

The solutions I have tried:
1. Clearing the fields manually - a bit problematic because the dropin seems to be using Hosted Fields iframes for multiple fields. Clearing the fields this way isn't trivial.
2. Using the `dropinInstance.clearSelectedPaymentMethod()` method. Doesn't seem to clear the fields.

Thank you!

**Comment by crookedneighbor** [comment]
👋 the only kinds of errors you'd experience here at the tokenization stage would be from failures to vault the card on the client (using a client token encoded with a customer id), or from putting in an invalid security code/postal code (depending on your fraud rules).

Insufficient funds response should only occur when you actually submit it for a transaction, which by that point, the card form will already be cleared because tokenization will have completed (unless you are specifically using `clearFieldsAfterTokenization = false` in the [create object](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~cardCreateOptions))

It's possible I'm missing something though.

**Comment by giedrius-timinskis** [comment]
Thanks @crookedneighbor, looks like I had some issues with my sandbox configuration. 
Appreciate the response 👍 
Closing the issue.
