### ISSUE TITLE
How to set the placeholder colors of the input fields?

### ISSUE THREAD

**Issue by jz222** [braintree/braintree-web-drop-in#626]
### General information

Version: 1.22.1

### Issue description

This is not directly an issue, however, I've been trying to set the placeholder color of the input fields of the dropin with CSS. Unfortunately, it didn't pick up the the custom color. I assume it's possible with hosted fields but I was curious if there was a way to set the placeholder color when using the dropin.

Thanks!

**Comment by crookedneighbor** [comment]
The reason that setting css rules on your page doesn't work is because the card inputs are contained within Braintree hosted iframes.

You will have to use the `card.overrides.styles` option when creating Drop-in: https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~cardCreateOptions

```js
braintree.dropin.create({
  card: {
    overrides: {
      styles: {
        "::placeholder": {
          color: 'red'
        }
      }
    }
  },
```
