### ISSUE TITLE
With "Customer Address" length of more than 50 characters 3D securcode does not work

### ISSUE THREAD

**Issue by bonny3** [braintree/braintree-web-drop-in#630]
General information

    SDK/Library version: 1.22.1
    Environment: Production
    Browser and OS 77.0.1 Win 10 Pro

Issue description:

I found the problem with Braintree
if I have an customer address with more than 50 characters the 3d securcode transaction does not go
and the error I sent you comes out

![Daniela](https://user-images.githubusercontent.com/19350758/85203177-377ade00-b30c-11ea-8f57-96090e7900c9.jpeg)

the 3D securcode popup does not arrive
and this error immediately comes out
how is it possible to solve the problem?

Thanks
Best Regards
Alessandro

**Comment by hollabaq86** [comment]
👋 @bonny3, thanks for reaching out! [EMVCo standards](https://www.emvco.com/wp-content/uploads/documents/EMVCo_3DS_Spec_v220_122018.pdf) dictate the 50 character limitation on addresses that our MPI provider has in place. You can resolve this issue in several ways, you could:
- add a validation to your checkout that limits your users from entering addresses with more than 50 characters.
- modify your `requestPaymentMethod` calls so that billing addresses are trimmed to 50 characters max
- modify your `requestPaymentMethod` calls to include extra characters in the `extendedAddress` parameter of your [billing address](https://braintree.github.io/braintree-web/3.58.0/ThreeDSecure.html#~billingAddress).
