### ISSUE TITLE
Unable to style input borders

### ISSUE THREAD

**Issue by mattcoz** [braintree/braintree-web-drop-in#645]
I'm trying to style the fields to match other input field on my site. I've tried adding border styles to my override settings with no luck. I can style pretty much everything else, but not borders. Oddly it seems that outline is supported, even though you can't see the outline from within the iframe. This could be used as a border if the outline-offset style was supported, but it's not.

**Comment by crookedneighbor** [comment]
That's because the borders are part of Drop-in itself, not overrides that are passed into the underlying card form iframes.

This should do what you want it to do:

```css
.braintree-form__hosted-field {
  border: 3px dotted red !important;
}
```

I'd be sure to check that your style overrides still apply whenever you update Drop-in, as we don't guarantee that the exact class names for the elements will be the same for every update. That said, they are largely stable and I don't expect them to change.
