### ISSUE TITLE
How to prevent front-end amount-fraud?

### ISSUE THREAD

**Issue by oli06** [braintree/braintree-web-drop-in#674]
### General information

* SDK/Library version: 1.24.0
* Environment: Sandbox
* Browser and OS: Chrome 86.0.4240.80 (64-bit) on MacOS 10.15.6

### Issue description

After entering account details in PayPal and calling `instance.requestPaymentMethod()` to request a new nonce I am able to successfully (SETTLED) call `chargePaymentMethod()` from my backend with a different amount.
For me - new to payment implementation - this is not understandable. How do I and/or Braintree prevent, that the amount in the DropIn UI is the same amount finally charged? 

#### Example:
A customer uses PayPal to pay for something 15€. At one time the front-end needs to notify the backend the newly generated nonce and the amount it should charge the customer. Since the nonce does not include information about the amount, the customer can easily interrupt the POST request to the backend and change the amount to a different value (e.g. 1€). 

For me it is unclear, why the nonce does not include information about the amount the customer is required to pay. Is there anything I am missing?

**Comment by crookedneighbor** [comment]
👋 

The amount submitted on the backend should always be looked up separately from the frontend. IE, if your customer chooses item `A` and item `B`, you should calculate the final price on your backend, rather than relying on an `amount` value passed from the frontend.

If the customer modifies the request on the front end to create the PayPal payment resource so that the amount is much lower price on the frontend during the checkout flow, the amount calculated on the backend for the final transaction.sale call will still be used to finish the sale. Either the sale will go through at the correct price, or you'll receive an error about the amount authorized when submitting it. 

In either case, this will prevent fraud.

If you need further help with this, please contact our support team: https://help.braintreepayments.com/

**Comment by oli06** [comment]
Thank you for your fast reply! That clearly makes sense.

As a follow-up question:
How is the customer protected, that I - as the developer / company - don’t charge the customer higher than required?

**Comment by crookedneighbor** [comment]
This is best to continue with our support team, as this has nothing to do with how the SDK functions.
