### ISSUE TITLE
Easier access to 3ds customer-canceled event

### ISSUE THREAD

**Issue by brandonburkett** [braintree/braintree-web-drop-in#690]
### Feature Request

When using the drop in ui with `threeDSecure: true`, it would be great if there was easier access to the `customer-canceled` event (when the user clicks cancel in the 3ds modal).

Currently I have to do this: 
```
braintreeInstance._threeDSecure._instance.on('customer-canceled', () => {...})
```

which feels like I am too deep into the internals.  It would be great if there was a a more direct path to attaching an event listener for this specific event.

Thanks!
Brandon

**Comment by hollabaq86** [comment]
👋 @brandonburkett you're totally right, we'll make a note to update this. Thanks for reaching out!

**Comment by brandonburkett** [comment]
Adding to this, it would also be great _not_ to automatically vault the card if `customer-canceled` is invoked when using drop in ui with a customer id.

**Comment by crookedneighbor** [comment]
@brandonburkett that's impossible, because the vaulting process on the client happens _before_ the 3ds lookup. If you want that more fine grained control, you should prevent the card from vaulting on the client at all and instead only vault on your server.

See the `card.vault` option when creating Drop-in: https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~cardCreateOptions

**Comment by brandonburkett** [comment]
Thank you and understood... went creating new subscriptions and needing to pass in the 3ds enriched nonce to subscription.create, it makes the most sense to vault client side (as customer payment tokens do not include 3ds info).

It was just an unexpected side effect when I noticed even the 3ds cancels were being vaulted, but I get it.

Still, aneasier hoo into customer-canceled from drop in ui would be great!

**Comment by crookedneighbor** [comment]
Added these events, but it's not been released yet. Re-opening this issue until the sdk is actually released.

**Comment by jplukarski** [comment]
This was added in version 1.27.0.
