### ISSUE TITLE
3ds recurring payment + drop in ui 

### ISSUE THREAD

**Issue by brandonburkett** [braintree/braintree-web-drop-in#691]
### General information

* SDK/Library version: 1.26.0
* Environment: Sandbox
* Browser and OS: Chrome 87.0.4280.141 and MacOS 11.1

### Issue description

We are in the process of adding 3ds support to our subscriptions / recurring payments and I had some confusion on the flow (in the docs). Is this correct:

1) drop in ui with 3ds params + request challenge
2) backend customer create with drop-in-ui 3ds enriched nonce + verifyCard true
3) take newly created customer payment token and create _another_ nonce on the backend
4) pass the second nonce into subscription create

It seemed odd to have go a two nonce route, but that is how the docs presented it.  Is this flow correct? 

Thanks

**Comment by crookedneighbor** [comment]
This won't work, because the 2nd nonce will no longer have the 3ds enriched data associated with it. What you want to do is:

1. create the customer before generating the client token
1. [generate your client token with the customer's id](https://developers.braintreepayments.com/reference/request/client-token/generate/#customer_id)
1. when you go through the 3ds process, the nonce will have been vaulted on the client automatically rather than on your backend and the resulting nonce will have the 3ds enriched data
1. pass that single nonce into the subscription create call


If you need further assistance, reach out to our support team https://help.braintreepayments.com/
