### ISSUE TITLE
3DS Confirmation code

### ISSUE THREAD

**Issue by Selvdrap** [braintree/braintree-web-drop-in#695]
### General information

* SDK/Library version: 1.26.0
* Environment: Sandbox
* Browser and OS: Firefox 85.0 and Chromium 88.0.4324.96 Arch linux +  88.0.4324.152 Android 9.0

### Issue description

The DropIn 3DS modal has a confirmation code input field which seems to clear any provided input. However everything is working in codepen example: https://codepen.io/braintree/pen/KjWqGx.

https://user-images.githubusercontent.com/24936843/108062941-8fb8da00-706b-11eb-8d81-955b01725125.mp4

**Comment by crookedneighbor** [comment]
Since everything is working in the codepen, that leads me to believe that there is something on your site that is interacting with 3ds modal in some way. Do you have a staging site we can view to reproduce issue? 

If you don't feel comfortable putting a link to your staging site on this public issue, feel free to reach out to our support team and reference this Github issue: https://help.braintreepayments.com/

**Comment by Selvdrap** [comment]
I managed to solve the issue. The problem was due to the feature of material ui dialogs enforcing focus. 
https://github.com/mui-org/material-ui/issues/17497

**Comment by crookedneighbor** [comment]
:+1: Thanks for the update.
