### ISSUE TITLE
Continuous loading

### ISSUE THREAD

**Issue by Khan294** [braintree/braintree-web-drop-in#710]
### General information

* SDK/Library version: 1.27.0
* Environment: Sandbox
* Browser and OS: Version 89.0.4389.82 (64-bit), Windows 10 Pro (64-bit)

### Issue description
I have freshly installed this package in my project (vue) but it keeps loading without any errors in console.
![image](https://user-images.githubusercontent.com/36960116/111229495-d3b9e300-8607-11eb-82de-9c58893fbcd3.png)

I can test my authorization key on example html code provided in this repo with success.
![image](https://user-images.githubusercontent.com/36960116/111229352-92293800-8607-11eb-99e4-b1bb4d987dc3.png)

I don't think this is same issue as [this](https://github.com/braintree/braintree-web-drop-in/issues/122) one as it is loading same CSS version in network tab
![image](https://user-images.githubusercontent.com/36960116/111228836-b6384980-8606-11eb-8c9c-5f10dfbc05c4.png)
and in package.lock
![image](https://user-images.githubusercontent.com/36960116/111229261-6efe8880-8607-11eb-85e9-84a2e03247f3.png)

I am not sure what else I can provide right now for further clarity.

**Comment by Khan294** [comment]
Downgraded to v1.26.1. Working fine now.

![image](https://user-images.githubusercontent.com/36960116/111334550-78cecd00-8695-11eb-9ced-44a0355f3b01.png)

**Comment by crookedneighbor** [comment]
Do you have a staging site where we can reproduce the issue? If there's an issue with 1.27.0, we want to fix it.

**Comment by Khan294** [comment]
Currently, I am testing it on local. I can put it up but will need some time.

I will email staging details to web-drop-in-beta@braintreepayments.com

**Comment by crookedneighbor** [comment]
If you're testing locally, my guess is you're loading it over the file protocol (as seen in your screenshot), rather than over an http server. I would recommend running an http server locally on your machine to do your testing, as some of the APIs that braintree uses in the browser do not function correctly over the file protocol.

If you are still having issues after spinning up an http server, please contact our support team and reference this issue rather than that beta email.

https://help.braintreepayments.com/
