### ISSUE TITLE
No nonce returned

### ISSUE THREAD

**Issue by wei2go** [braintree/braintree-web-drop-in#751]
### General information

* SDK/Library version: 1.22.1
* Environment: Production
* Browser and OS: Unknown

### Issue description

I have this issue that we did not receive the nonce from Braintree for a single particular user. The form has been running for about a year with no issue, and this was the first time we had this kind of problem. This user also looks legitimate (not a spam) based on the information collected. Also there was no error returned by the callback of "requestPaymentMethod", otherwise, the form wouldn't submit and we won't even notice this issue. Please see part of the code below:

```
instance.requestPaymentMethod(function (err, payload) {
    if (err) {
        // Error handling
        // ...
        return;
    }

    // Add the nonce to the form and submit
    $("#nonce").val(payload.nonce);

    $("#myForm").submit(); // for some reasons, we don't get the 'nonce' submitted to the server for only one particular user
});
```

My question is: under what circumstances that the drop-in UI won't trigger an error, and won't respond with a nonce in the payload either? Is there any information we can collect from Braintree dashboard or something to find out what exactly happened to this user's payment?

**Comment by crookedneighbor** [comment]
There are no cases I can think of where this should happen. Do you happen to know what kind of payment method it was? (credit card, paypal, apple pay, etc)

**Comment by wei2go** [comment]
> There are no cases I can think of where this should happen. Do you happen to know what kind of payment method it was? (credit card, paypal, apple pay, etc)

I don't have this specific information, but credit card and paypal are the only available options.

**Comment by crookedneighbor** [comment]
I can think of 0 cases where this would happen under normal circumstances.

I guess it's possible that the customer had their dev tools in their browser open and removed the nonce before it was sent to the server, but that seems unlikely if this was just a normal customer.

Since this seems to be an isolated incident, I'm going to close this for now. I would keep an eye on it and if it continues to be a problem, reach out to our support team in the future so we can figure out what's going on. https://developer.paypal.com/braintree/help
