### ISSUE TITLE
The Credit Card form is being collapsed on requestPaymentMethod call

### ISSUE THREAD

**Issue by andrew-ignatiev** [braintree/braintree-web-drop-in#753]
### General information

* SDK/Library version: ^1.31.0
* Environment: Sandbox and Production
* Browser and OS: 91.0.4472.164 (Official Build) (x86_64) on MacOS Big Sur 11.4

### Issue description

The Credit Card form is being collapsed on [requestPaymentMethod](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#requestPaymentMethod) call. It doesn't seem to be correct behaviour because that method is designed to get just info such as nonce of current selected/requestable method. 

I've reproduced the issue in CodePen https://codepen.io/andrew-sp/pen/rNmGzNq

**Comment by crookedneighbor** [comment]
This is by design. All the other payment methods have their own entry point for starting the flow (ex: a PayPal button or an Apple Pay button). Credit cards do not. We made the design decision early on to have `requestPaymentMethod` for credit cards trigger the submit action and then resolve with the nonce. When we add additional form based payment methods (us bank account comes to mind), we'd employ the same strategy.

You can make the branded payment methods provide the nonce immediately upon completion by utilizing the `paymentMethodRequestable` event. See the example labeled: `Automatically submit nonce to server as soon as it becomes available` [in the client SDK docs](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html).

I agree that this fundamental difference between form based payment methods and branded button payment methods is a little strange, and it's something we're thinking about for v2 of Drop-in.

I'm going to leave this issue open and mark it as v2.

**Comment by andrew-ignatiev** [comment]
Hi @crookedneighbor , thank you for your reply. 

We use `requestPaymentMethod` on `paymentMethodRequestable` event to detect on whether the selected (`requestable`) payment method from the list is already vaulted or not to proceed with custom vault logic (e.g. show/hide checkbox "Save for your next payment in checkout) via [Server API](https://developer.paypal.com/braintree/docs/reference/request/transaction/sale#options.store_in_vault_on_success) in generic way for PayPal (with recently released feature [vaultPayPal](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~paypalCreateOptions) and Credit Card.

Is there any other API which can provide `vaulted` flag but don't collapse the credit card form which customer want to change after failed payment attempt?

**Comment by crookedneighbor** [comment]
You can use `clearFieldsAfterTokenization: false` in the `card` options to prevent Drop-in from clearing the fields after tokenizing the details (see https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~cardCreateOptions), but I don't think we have anything as specific as the flow you want, since the customer would still need to return to the card form to see the details. (it wouldn't lose the data, but it wouldn't prevent it from collapsing in the first place)

My recommendation would be to fork Drop-in and create your own version if you specifically need that flow.
