### ISSUE TITLE
updateConfiguration issue

### ISSUE THREAD

**Issue by skiner** [braintree/braintree-web-drop-in#769]
### General information

* Drop-In version:  1.31.2
* Environment: Sandbox and Production
* Browser and OS: Chrome 93.0.4577.82 (Official Build) (x86_64)

### Issue description
If you first select payment method Apple Pay and then apply `updateConfiguration` function, the payment method is hidden from the list of payment methods, the same for Google Pay.

Sample code:
```
instance.updateConfiguration('applePay', 'paymentRequest', {
            total: {
                label: 'My Payment',
                amount: amount.toString()
            }
});
```

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll take a look.

**Comment by crookedneighbor** [comment]
I think what you're experiencing is expected behavior.

When you go through the payment method flow for PayPal, Apple Pay, or Google Pay, you get a payment method nonce representing the configuration at the time of completion. If you then update the configuration, any previously completed authorization are removed. This is to prevent the customer from submitting a payment method authorized under one set of circumstances (such as the amount being set to $5) for a transaction under a new set of circumstances (such as the amount being set to $500).

If you're seeing something else, let me know and I'll re-open this ticket.
