### ISSUE TITLE
Cardholder name is not present

### ISSUE THREAD

**Issue by beworker** [braintree/braintree-web-drop-in#77]
Hey! Cardholder name is not present in the drop-in UI. Is this expected behaviour? This looks kind of unusual. Can the input field for cardholder name be enabled?

**Comment by crookedneighbor** [comment]
This is expected behavior. Card holder name is not required to transact on a credit card.

We'll keep your request in mind for the future to allow the Drop-in UI to have an option to provide an input for card holder name.

For now, if you want to collect card holder name on your site, you can include an input outside of the Drop-in form.

**Comment by beworker** [comment]
I just wanted to be sure it has no impact on the transaction from risk and fraud point of view later on. But if it's expected behaviour, then it's fine. Thanks for the explanation.

**Comment by skunkworks** [comment]
We are closing this issue for now but welcome feedback from others on this enhancement.

**Comment by crookedneighbor** [comment]
Got another request for this. Linking here for reference: https://github.com/braintree/braintree-web/issues/54#issuecomment-306828314
