### ISSUE TITLE
Possible to bypass unsupported 3DS card?

### ISSUE THREAD

**Issue by heekzz** [braintree/braintree-web-drop-in#813]
### General information

* SDK/Library version: 1.33.1
* Environment: Sandbox
* Browser and OS Chrome 100.0.4896.127 (arm63) on MacOS 12.1

### Issue description

When using the Braintree Web drop-in with 3DS2 enabled using the init 
```javascript
dropin.create({
  // insert your tokenization key or client token here
  authorization: token,
  container: "#container",
  threeDSecure: true,
  paypal: {
    flow: "checkout",
    amount: "100",
    currency: "USD",
    locale: "en-US",
  },
});

```
and trying to pay with a Discover card which is not supported by Braintree when using 3DS ([According to this article](https://developer.paypal.com/braintree/articles/guides/fraud-tools/3d-secure#card-brands)).

When doing the `let payload = dropInInstance.requestPaymentMethod({ threeDSecure: { ... } });` the payload says that `payload.liabilityShifted = false`; and we cannot use the card even though the configuration says we support it. The `payload.threeDSecureInfo.status` also says `unsupported_card`.

Is it possible to bypass 3DS in this case without recreating the drop in instance and forcing the user to enter their details again?

I have tried to disable the 3DS config by calling `dropInInstance.updateConfiguration('threeDSecure', false);` (taken from [this doc](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#updateConfiguration)) but it doesn't seems to disable the 3DS.

### User Story
> As a merchant I want to bypass 3DS when a customer enters a card (Discover) where support for 3DS of the card is missing in Braintree

**Comment by nyansf** [comment]
@heekzz Did you find a solution for this? We're facing the same issue with discover cards being blocked since 3DS is not supported, haven't heard back from support yet.

**Comment by hollabaq86** [comment]
👋 @heekzz thanks for reaching out and apologies for the delay. Rather than bypass 3DS on the client, you can [bypass 3DS being required](https://developer.paypal.com/braintree/docs/guides/3d-secure/server-side#requiring-3d-secure) on your server-side workflow using the [parameter](https://developer.paypal.com/braintree/docs/reference/request/transaction/sale#options.three_d_secure.required) Options-> Three D Secure -> Required.

Depending on the regulatory environment you're operating in (PSD2 comes to the front of my mind), you may want to consider [contacting support](https://developer.paypal.com/braintree/help) for assistance because they have deeper knowledge on regulatory constraints.
