### ISSUE TITLE
The button for checkout with paypal does not appear on some screen resolutions

### ISSUE THREAD

**Issue by devjayprakash** [braintree/braintree-web-drop-in#820]
### General information

* SDK/Library version: 1.22.4
* Environment: Production and Dev
* Browser and OS 

### Issue description

On device with 1520 X  720 the checkout with paypal button get's chopped off or does not appear.

Please check this image to see the issue

https://www.dropbox.com/s/lmlbom148izkf9j/jay%20Screenshot-20%20at%202.06.08%20PM.png?dl=0

**Comment by hollabaq86** [comment]
👋 @devjayprakash thanks for reaching out, and apologies for the delay in our response. Can you confirm what html elements the drop-in is being generated within? From your screenshot that looks like some kind of pop-up, so I wanted to confirm so that we can try to replicate the issue.

If you don't feel comfortable letting us know in this public issue, please feel free to [contact Support](https://developer.paypal.com/braintree/help) referencing this issue and we can coordinate through them.

**Comment by hollabaq86** [comment]
for internal tracking, issue 353

**Comment by cgdibble** [comment]
Hey, @devjayprakash, it sounds like those is more directly related to the interaction you're having with the PayPal SDK itself.

We'd recommend reaching out to that SDK directly here: https://github.com/paypal/paypal-smart-payment-buttons/
This might be a quick reference to help, but regardless reaching out to the Smart Payment Buttons repo directly is a good idea: https://developer.paypal.com/sdk/js/reference/#link-size

Please re-open if further investigation narrows things down to our dropin.
