### ISSUE TITLE
THREEDS_NOT_ENABLED_FOR_V2

### ISSUE THREAD

**Issue by DidoMarchet** [braintree/braintree-web-drop-in#823]
### General information

* SDK/Library version: 1.33.4
* Environment: Sandbox

### "3D Secure failed to set up."

The dropin start to return this error:
```javascript error
DropinError {name: 'DropinError', message: '3D Secure failed to set up.', _braintreeWebError: BraintreeError}
message: "3D Secure failed to set up."
name: "DropinError"
_braintreeWebError: BraintreeError
code: "THREEDS_NOT_ENABLED_FOR_V2"
details: undefined
message: "3D Secure version 2 is not enabled for this merchant. Contact Braintree Support for assistance at https://help.braintreepayments.com/"
name: "BraintreeError"
type: "MERCHANT"
```

and I don't know how to solve it.
Two weeks ago circa it didn't return this error.

Do you have any suggestion?

I try to ask to the support but no way to have a answer.

Thanks in advance and kind regards,

Davide

**Comment by cgdibble** [comment]
@DidoMarchet hello! Thanks for submitting this. The error itself has all the information you need, so check the `message` property on it.

The problem is you don't have that functionality enabled for your merchant account.

From the [Configuration Docs](https://developer.paypal.com/braintree/docs/guides/3d-secure/configuration):
> In sandbox, 3D Secure is automatically enabled for all merchants.

Can you confirm you are in fact running this against the sandbox environment and not production? Otherwise, we'd have to be able to see a sample or test site that demonstrates the issue to be able to provide more info.

**Comment by DidoMarchet** [comment]
> @DidoMarchet hello! Thanks for submitting this. The error itself has all the information you need, so check the `message` property on it.
> 
> The problem is you don't have that functionality enabled for your merchant account.
> 
> From the [Configuration Docs](https://developer.paypal.com/braintree/docs/guides/3d-secure/configuration):
> 
> > In sandbox, 3D Secure is automatically enabled for all merchants.
> 
> Can you confirm you are in fact running this against the sandbox environment and not production? Otherwise, we'd have to be able to see a sample or test site that demonstrates the issue to be able to provide more info.

Hi @cgdibble I had a mistake with the configuration and you are correct. 
The issue no longer exist and really thanks.

Thanks and kind regards,

Davide
