### ISSUE TITLE
DropIn UI failed to render in Edge for enterprise users with restricted access in Windows 10

### ISSUE THREAD

**Issue by davidtomcik** [braintree/braintree-web-drop-in#834]
### General information

* SDK/Library version: 1.33.4
* Environment: Production
* Browser and OS: Microsoft EdgeVersion 106.0.1370.52 (Official build) (64-bit) on Microsoft Windows 10 Enterprise

### Issue description

We found a problem with Braintree DropIn UI in Edge (chromium) browser for employees of enterprise with restricted access to their devices. The method "create(dropInOptions.value)" returns a promise that rejects the creation UI with the message "All payment options failed to load" and the UI is hidden after a while. There is a message "chunk-vendors.js:70515 GET https://assets.braintreegateway.com/web/3.86.0/html/hosted-fields-frame.min.html net::ERR_CACHE_WRITE_FAILURE 200" in the console, please see the screenshot in the attachment.

Braintree DropIn UI works fine when the cache is disabled in the dev tools and the same is for the Edge (chromium) browser within the incognito mode. Unfortunately, the employees do not have the right to use these workarounds. Other browsers (chrome, firefox,..) also work fine.
![Edge-BTDropIn-create-failed](https://user-images.githubusercontent.com/72572079/198038517-e65c7582-9873-4585-b336-190aefb7a5cc.png)

**Comment by hollabaq86** [comment]
👋 @davidtomcik thanks for reaching out, unfortunately this is nearly impossible for us to reproduce/troubleshoot  because everyone's network settings are different, and we may not be able to replicate those network settings in our location.

I suggest reviewing your network's [security settings](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/mapping-your-deployment-goals-to-a-windows-firewall-with-advanced-security-design/) and start toggling each restriction on/off to test the payment workflow in Edge and see if you continue to encounter the issue. If you can pinpoint the setting that's causing the issue, that can probably guide you to any reference docs for Edge that may explain what they're doing that's preventing the drop-in from loading.

If you can, please [contact Braintree Support](https://developer.paypal.com/braintree/help) referencing this issue and your findings, as that can help us identify possible updates we can make in the library to account for Edge browsers doing something differently than other browsers.
