### ISSUE TITLE
Dynamic PP amount?

### ISSUE THREAD

**Issue by NinoSkopac** [braintree/braintree-web-drop-in#87]
```
braintree.dropin.create({
            authorization: 'sandbox_XXX ',
            selector: '#braintree-dropin',
            paypal: {
                flow: 'checkout',
                amount : this.getMoney(), // <== THIS
                currency: 'EUR'
            }
        }
```

Is it possible to have the amount property dynamic? At the moment the amount value is bound on construct time, and since we cannot do byref assignment in JS, this is a problem.

I'm looking for a way to do something like `braintree.paypal.amount = XYZ`

At the moment, I am emptying the #braintree-dropin and re-creating it, but that's obviously shit then all CCs data are lost. So, for example, if someone changed his mind about how much they wanna spend/pay, and I reconstruct the dropin and the CC data are lost.

**Comment by lilaconlee** [comment]
At the moment, the only way to update the PayPal amount is to create a new instance. We're still working on improving the API, so we'll definitely keep that in mind and let you know here if we end up adding that functionality. Thanks for the feedback!

**Comment by intelliot** [comment]
With `flow: 'checkout'`, the customer is agreeing to a specific amount during the PayPal checkout flow. If the amount property were dynamic, then the customer's prior PayPal authentication would be for the wrong amount.

We recommend one of the following:
1. Wait until the amount is finalized before creating Drop-in.
2. Use [the Vault flow](https://developers.braintreepayments.com/guides/paypal/vault/javascript/v3#invoking-the-vault-flow). This initiates a billing agreement and the customer will see different text.
3. Re-create Drop-in when the amount changes, as you currently are. If the customer has entered complete CC data, you can use `requestPaymentMethod` to tokenize the CC first.

@NinoSkopac Does one of these options work for you?

**Comment by NinoSkopac** [comment]
@intelliot Don't like either of these, I just want to be able to set the amount dynamically. The checkout `amount` is shown in the PP pop-up, so I don't know  why would that be a bad idea.

**Comment by crookedneighbor** [comment]
I think there's some confusion here about terms. This is the basic lifecycle of Drop-in.

1. You set up drop-in and pass the PayPal config in.

2. Customer logs into their PayPal account.

3. You request the payment method and send the nonce to your server.

Between steps 1 and 2, you _could_ safely update the PayPal config because the customer has not yet logged in. However, the case we're worried about is between steps 2 and 3. If the config options have changed, it won't be reflected in the authenticated account, that customer will still have authorized only the original amount. You as a merchant don't have much visibility about whether or not the customer has logged in or not.

I think a pre-requisite to set the options dynamically will be to provide some additional lifecycle hooks, so you can update your page and prevent the customer from making changes that would update the amount _after_ they have already logged in.

**Comment by crookedneighbor** [comment]
You can now use `updateConfiguration` to dynamically update your PayPal settings: https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#updateConfiguration

```js
dropinInstance.updateConfiguration('paypal', 'amount', '10.00');
```

This was just released with version 1.1.0

**Comment by NinoSkopac** [comment]
@crookedneighbor Thanks for the update. Will this trigger PP component destruction and re-construction? This is how I internally had to do it since there was no API for it. If not, I'm happy to abolish my manual way of doing it in favor of this.

**Comment by crookedneighbor** [comment]
If the customer has not logged in with their PayPal account yet, the change will take place without any side effects.

If the customer has already logged in, their authorized PayPal account will be removed from Drop-in and they will have to log in again. 

The exception to this behavior is if the authorized PayPal account was vaulted, then that same PayPal account can still be used even after updating the configuration. (since vaulted PayPal accounts use Billing Agreements, which don't care about authorizing specific amounts)

**Comment by NinoSkopac** [comment]
So, it is better than what I'm doing. Thanks, putting this on my todo list.
