### ISSUE TITLE
updateConfiguration cannot update credit card properties

### ISSUE THREAD

**Issue by phigrofi** [braintree/braintree-web-drop-in#906]
### General information

* SDK/Library version: 1.34.0
* Environment: sandbox and production
* Browser and OS: Mac OS X 13.5.1, Brave 1.59.117 or Chrome 118.0.5993.88

### Issue description

After initializing the dropin, our users are able to select if they want a subscription or a single purchase. If they only do a single purchase we do not want to vault their payment method. 
For paypal this works fine: 
```js
dropinInstance.updateConfiguration("paypal", "flow", "checkout");
```
or
```js
dropinInstance.updateConfiguration("paypal", "flow", "vault");
```

We would like to do the same for credit cards, but we can't figure out how to use `updateConfiguration` in this case. 

We tried: 
```js
dropinInstance.updateConfiguration("card", "vault", { vaultCard: true }); 
```

But this does not seem to have an effect. Also the documentation of `updateConfiguration` states that allowed values for `property` are 
`paypal, paypalCredit, applePay, or googlePay`
but not `card`. 

I would be grateful for any hint, how to achieve this.

**Comment by jplukarski** [comment]
Hey @phigrofi , thanks for bringing this question to us. You are correct that `updateConfiguration` is only available for `paypal`, `paypalCredit`, `applePay`, or `googlePay`. What I can suggest is instead of vaulting cards on the client-side, to instead conditionally vault the cards on your server side using [`paymentMethod.create()`](https://developer.paypal.com/braintree/docs/reference/request/payment-method/create/node) with the nonce that is generated in the cases where you would like to vault the payment.

I hope that suggestion works for you. Let us know if there are any additional questions.

**Comment by jplukarski** [comment]
You're welcome, @phigrofi. I am going to close this issue. If you have any additional questions feel free to open a new one or [reach out to our Support Team](https://developer.paypal.com/braintree/help).
